# Autogenerated wrapper script for libzenohc_jll for aarch64-linux-gnu
export libzenohc

JLLWrappers.@generate_wrapper_header("libzenohc")
JLLWrappers.@declare_library_product(libzenohc, "libzenohc.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libzenohc,
        "lib/libzenohc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
